### ISSUE TITLE
Reevaluate use of Slack

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#17]
Slack has a lot of great features, but it makes on-boarding more difficult and doesn't allow lurking. Should we explore alternatives.

**Comment by kwurst** [comment]
And it's not open source ;-)

**Comment by kussmaul** [comment]
Neither is GitHub. :)

 

Clif
---
Clif Kussmaul   <mailto:clif@kussmaul.org> clif@kussmaul.org   <http://kussmaul.org/> http://kussmaul.org  +1-484-893-0255  EDT=GMT-5  (he/him)

**Comment by HeidiEllis** [comment]
And it isn't accessible.

On 4/19/19 10:11 AM, Stoney Jackson wrote:
**** EXTERNAL MESSAGE ****

Slack has a lot of great features, but it makes on-boarding more difficult and doesn't allow lurking. Should we explore alternatives.

**Comment by kwurst** [comment]
We may want to hold off on choosing a new chat tool until we decide whether we are moving the project off GitHub to GitLab. That probably won't be decided until near the end of the summer.

**Comment by StoneyJackson** [comment]
Alternatives:

- [ ] Riot
- [ ] Gitter
- [ ] Discord

**Comment by kwurst** [comment]
https://about.gitlab.com/2017/03/15/gitter-acquisition/

**Comment by StoneyJackson** [comment]
Re Gitter: it allows "Sign in with GitLab" and "Sign in with GitHub" and "Sign in with Twitter". Since it supports the two platforms we've identified so far, this makes it a more attractive option. Need to learn more about its features.

**Comment by StoneyJackson** [comment]
https://drewdevault.com/2015/11/01/Please-stop-using-slack.html 

Interesting read. I agree that one of Slack's main problem is that it is opaque. And that's not good for an open-source community.

I think the author misses the mark about the problems that Slack solves. The biggest problem Slack solves is usability and user experience. Want to send an image? Just drag it in. Want to integrate it with GitHub? Just search for the app in Slack, add it, it walks you through the rest. I think there is a tendency among developers to undervalue usability and user experience. As a developer I don't want to fight with my tools to get value out of them just because I'm a developer and probably have the know-how to win that fight.

The author is opposed to Gitter for the same reasons they are against Slack. However, in my estimation, Gitter is somewhere between Slack and IRC for usability. And it doesn't suffer from the opaqueness problem that Slack does.

On the accessibility front... here is an interesting article: https://developer.paciellogroup.com/blog/2015/07/anybody-can-be-an-a11y-slacker/ . My summary is that although Gitter is not without problems, it is more accessible that Slack.

**Comment by StoneyJackson** [comment]
At the retreat, after much discussion we landed on gitter. It is designed to be used with GitHub and GiLlab and it's radically transparent (one can lurk without even joining a channel). Although it lacks some of the cool features of slack and discord. 

We disqualified slack because of its lack of transparency and barrier to entry. We disqualified discord because we found its branding to gamers may be off-putting, may send the wrong message, may disenfranchise non gamer populations while priveleging gamers; without evidence either way we felt it was best to avoid the risk of an issue. We disqualified riot because of its clunky interface. We disqualified rocket because of its server/hosting complexity. We disqualified IRC for it's lack of history and integrations.

We did discuss but left unresolved whether one or more chat channels are necessary or desirable. We can reevaluate this after observing its use.

To do:

- figure out how to create and organize gitter channels
- determine a naming convention
- create initial channels
- announce the move
- close slack

**Comment by StoneyJackson** [comment]
Over email, a concern was raised about the permissions Gitter wants for GitHub and GitLab. It appears that this problem isn't limited to Gitter. I think It is a longstanding issue for all 3rd party applications that want to integrate with GitHub and Gitlab.

* https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/oauth-scopes.md
* https://github.com/dear-github/dear-github/issues/113

I've run into this before and had to decide how much I trusted the application. For example, I have granted Travis CI full access to all my repositories. But it really only needs read-only access to specific repositories.

I'm not sure what the solution is. Suggestions welcome.

**Comment by kwurst** [comment]
Opinions from POSSE attendees in June 2019:

```
- Discourse versus Gitter
  - POSSE folks had reservations about Gitter
    - Privacy/plagiarism with Gitter having access to 
    - FERPA issues related to having access to repos
  - Discourse:
    - POSSE folks weren’t concerned with the “gaming” flavor of discourse
    - Might also be a positive as they could ask students for help in setting up
  - The choice needs to be accessible
    - Both for people with disabilities
    - Also for people in countries such as China
```

**Comment by StoneyJackson** [comment]
I'm assuming we're talking about [Discord](https://discordapp.com/) and not [Discourse](https://www.discourse.org/).

A brief aside about [Discourse](https://www.discourse.org/)... if our issue trackers get to noisy with Q&A and discussions, we might want to consider Discourse.

Returning to [Discord](https://discordapp.com/) and Slack.

- Privacy (with regard to Gitter's access to private repositories) - A workaround: When using Gitter, use a separate GitHub/GitLab/Twitter account that has no repositories or projects associated with it. This account could even be "anonymized", or it could be related to your original account. For example, if I don't want Gitter to have access to my private repositories on GitHub, I could create an account like StoneyJacksonGitter . Which of course would not have any repositories associated with it. And then always sign in with that account for Gitter. (One could also do this with Twitter instead, as Twitter has no GitHub projects associated with it.) There may be other unforeseen complications with this workaround, as I have not tried it.

- Plagiarism - I don't understand the concern with Gitter and Plagiarism. I would need a use-case.

- FERPA - my strategy
    - Never publicly talk about or name a course/class on-line; just treat it as work.
    - Never name anything public or that may become public based on a course/class or an institution.
    - Allow folks to use anonymized accounts for GitHub, GitLab, Gitter, etc.
    - Allow folks to use anonymized information for Git commits (for example: `git config --global user.name "Clown Fish"` and `git config --global user.email "clown.fish@gmail.com"`).
    - At the outset, Inform members of the above and why you are allowing it so they can make an informed decision from the beginning.
    - Never publicly evaluate/grade

- Discord - Interesting comments. Make me feel a bit better about the prospect of using Discord.

- Censorship in China (is how I interpreted "... accessible ... for people in countries such as China") - I'm not sure what to do here. Please help.

- Is accessible for people with disabilities - The only information I can provide is the following
    - A post and a discussion that is following the accessibility of Discord for blind users: https://support.discordapp.com/hc/en-us/community/posts/360032435152-Discord-Accessibility-for-blind-users
    - Gitter
        - I don't know how accessible the native Gitter interface is (or its mobile apps).
        - There is an IRC bridge for Gitter (https://irc.gitter.im/). I'm not suggesting that this interface provides parity for blind users; but this bridge is possible because of Gitter's API. So there may be hope even if Gitter's native interfaces are not.

**Comment by StoneyJackson** [comment]
@kwurst I think you said you created a Discord server named "OpenPath".  I tried to search for it. But no results (see screenshot below). Do I have the right name? Am I doing it right?

![image](https://user-images.githubusercontent.com/1394670/60307825-33dc9300-9914-11e9-8fc4-bd68e6a4dbb4.png)

**Comment by StoneyJackson** [comment]
@kwurst invite link to LibreFoodPantry discord server: https://discord.gg/h5RdTR4

**Comment by StoneyJackson** [comment]
All, we'll try Discord for our next coordinating committee meeting on Tuesday, July 9th. See previous comment for invite link.

**Comment by HeidiEllis** [comment]
From a conversation with Diane Tran:
 I do have experience with the platform although I am not positive how appropriate it will be as a means of communication professionally. Discord is a less formal-professional version of Slack, with its target audience being primarily to the gaming communities. Slack is very similar to Discord with mostly the same functionalities.


Categories | Slack | Discord
-- | -- | --
Target audience | Business | Gamers
Primary communication | Text communication | Voice communication
Pricing | Free plan Standard: $6.67/month (per user) Plus: $12.50/month (per user) | Free plan Nitro: $4.99/month (per user)
Message history limit | 10,000 messages | Unlimited
Video conferencing | Up to 2 people in Free plan Up to 15 people in Paid plans | Up to 8 people in Free plan
Screen sharing | Yes | Yes
Storage limit | 5GB in Free plan 10GB - 20GB in Paid plans | Unlimited
File upload limit | 1 GB | 8MB in Free plan 50 MB in Nito Plan
Channel members limit | Possible limit notification starting at 8.5K members | Default online concurrent user limit is 5,000
Conversation threads | Yes | No
Voice only channels | No | Yes
Push to talk | No | Yes
Conversations | Private channels Public channels Direct messages | Text channels Voice channels Direct messages
Notifications | Customization open to user | Customization open to user
Integrations | Able to connect to 800+ apps and tools directly Allows notifications from software/tools directly into team communication tool(s) | Does not directly connect your apps at work

Original source: https://www.chanty.com/blog/discord-vs-slack/

Both platforms are very similar, although the main difference is the target audience. Discord has become somewhat of a synonym for the gaming community, and thus most of the servers on Discord are dominated by gamers. While it is possible to use Discord for HFOSS communications, it will not be terribly likely to find other HFOSS communities easily. Discord is also focused on voice-chat communications due to the nature of the gaming community, versus Slack which is more text-based.


Interface-wise, both are similar once more. Contacts are organized to the left while the conversation happens to the right. Slack organizes their interface in an easier to read format; all the direct conversations, channels and apps are more visible compared to Discord. Discord's channels and conversations are separated and organized under different menu tabs.

**Comment by StoneyJackson** [comment]
@HeidiEllis @dtran2017 Thanks for the analysis!

Another point I've mentioned on calls/meetings, but want to capture here...

Discord has more fine-grained control over permissions and roles than does Slack. You can create custom roles and associate them with a set of permissions. Then assign roles to users.
https://support.discordapp.com/hc/en-us/articles/206029707

For example, we could set it up so that anyone can read any channel, but can only send messages to `#general`, and only at a throttled rate (to avoid spam). But anyone with the `member` role can post to any channel. 

In fact, this is one of the main reasons Discord makes our short list. It allows high transparency, while helping to address spam. This makes on-boarding easier.

In contrast, Slack has a limited set of predefined roles (https://get.slack.help/hc/en-us/articles/360018112273) with a predefined set of permissions (https://get.slack.help/hc/en-us/articles/201314026-Roles-and-permissions-in-Slack).

**Comment by HeidiEllis** [comment]
Just to note, @DianeTran did the analysis. I just copied the information.

On 7/31/19 2:45 PM, Stoney Jackson wrote:
**** EXTERNAL MESSAGE ****

@HeidiEllis<https://github.com/HeidiEllis> @dtran2017<https://github.com/dtran2017> Thanks for the analysis!

Another point I've mentioned on calls/meetings, but want to capture here...

Discord has more fine-grained control over permissions and roles than does Slack. You can create custom roles and associate them with a set of permissions. Then assign roles to users.
https://support.discordapp.com/hc/en-us/articles/206029707

For example, we could set it up so that anyone can read any channel, but can only send messages to #general, and only at a throttled rate (to avoid spam). But anyone with the member role can post to any channel.

In fact, this is one of the main reasons Discord makes our short list. It allows high transparency, while helping to address spam. This makes on-boarding easier.

In contrast, Slack has a limited set of predefined roles (https://get.slack.help/hc/en-us/articles/360018112273) with a predefined set of permissions (https://get.slack.help/hc/en-us/articles/201314026-Roles-and-permissions-in-Slack).

**Comment by kwurst** [comment]
I vote for Discord.

I admit it has some image/culture issues, but I think we can counter those by warning the students about those before having them join, being explicit about our own code of conduct, and stressing that we police our own channels and will be careful about making our channels' culture open and welcoming.

**Comment by StoneyJackson** [comment]
I vote for Discord.

**Comment by HeidiEllis** [comment]
I'm not sure. And I'm on vacation so don't have a lot of time to think about this. I'm concerned about making a decision without everyone on board.  Lori and Darci, what do you think?

On 8/4/19 2:04 PM, Karl R. Wurst wrote:
**** EXTERNAL MESSAGE ****

I vote for Discord.

I admit it has some image/culture issues, but I think we can counter those by warning the students about those before having them join, being explicit about our own code of conduct, and stressing that we police our own channels and will be careful about making our channels' culture open and welcoming.

**Comment by StoneyJackson** [comment]
We really need to make a decision on this (as well as #54). Much of the documentation and setup we've been working on requires double effort or must be put on hold until these issues are resolved. This is time and energy we could have been, and need to be, spending elsewhere.

I understand that this is a difficult decision because no one is completely satisfied with any of the options we have identified. But having deliberated on these issues for over 3 months, I don't think we're going to find a perfect solution.

I would have preferred to decide this in a meeting by consensus. But time and schedules are not on our side. So I think a remote vote is the best way to give everyone a chance to voice their opinion/preference and make a decision.

**Comment by hislop** [comment]
I have infrequent net this week.  One suggestion:  I think we should give extra weight to the votes of the women on the team. Choice of discord seems to require the right choice for our goal of attracting more female students.



Sent via the Samsung GALAXY S®4 Active™, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by HeidiEllis** [comment]
I completely agree that we need to make a decision. The fall semester is swiftly approaching.  Just want to make sure that all voices are heard. I vote with whatever Darci and Lori decide.

H.

On 8/5/19 12:52 PM, Stoney Jackson wrote:
**** EXTERNAL MESSAGE ****

We really need to make a decision on this (as well as #54<https://github.com/LibreFoodPantry/Community/issues/54>). Much of the documentation and setup we've been working on requires double effort or must be put on hold until these issues are resolved. This is time and energy we could have been, and need to be, spending elsewhere.

I understand that this is a difficult decision because no one is completely satisfied with any of the options we have identified. But having deliberated on these issues for over 3 months, I don't think we're going to find a perfect solution.

I would have preferred to decide this in a meeting by consensus. But time and schedules are not on our side. So I think a remote vote is the best way to give everyone a chance to voice their opinion/preference and make a decision.

**Comment by kwurst** [comment]
@cradkowski figured out how to turn off the stupid random messages when new people join the server. I turned it off on both LibreFoodPantry and OpenPath servers. 🎉

**Comment by lpostner** [comment]
Sorry for being late to the conversation.  I'm really torn as I don't know what the right call is (and I'm not comfortable making the call - it should be a community decision/discussion).  But based upon our coordinating committee meeting yesterday I really like the idea of turning this into a research question.  We don't know how students will react, so why not try it and collect data to see if our hypotheses are correct?  If we are willing to go in this direction, then I'm for giving Discord a try in the fall and seeing the reaction.  Thoughts?

**Comment by burdged** [comment]
I've continued to be on the fence about using Discord, but really like the idea of turning this into a research question to study how our students (especially female students) react to using it. I vote to try it next year as long as we have developed the research questions by the beginning of the fall term.

**Comment by StoneyJackson** [comment]
@burdged Can you clarify "next year"?

**Comment by burdged** [comment]
Sorry, this is my subconscious attempt to think that the upcoming academic year is further away than it really is!! I mean this upcoming school year.

**Comment by kwurst** [comment]
I figured out how to turn off the Activity Feed on Discord. This is the screen that shows what games you are playing. 🎉 

Under Settings>Appearance turn off the Show Activity Feed switch.

The activity feed will still show when you start it up, until you click on Home (the controller face) and choose Friends. But Friends will be the only option now, and when you start it up from now on you will see your Friends List.

This is a personal setting that each person will have to make, there is no way for us to turn it off on a per-server basis.

**Comment by StoneyJackson** [comment]
So if we go with Discord, we might want to create a discord tips page.

**Comment by kwurst** [comment]
Yup. If we go with Discord, I am envisioning a "Why Discord, and how to configure it" page.

**Comment by hislop** [comment]
I like the research idea, and I’m not hearing any definite “no” votes for discord.  So I guess we try discord.

**Comment by StoneyJackson** [comment]
Agreed: Discord

This was a tough one. Remember "It's not what you know; it's what you want to learn". For us, we know Slack is problematic for transparency. Now we want to learn if Discord can work.

Thanks all for voting and helping to make this decision!
